---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _snmpd_snmpwalk_package:
      default:
        - snmp
      Alpine:
        - net-snmp-tools
      RedHat: &redhat_snmpwalk_package
        - net-snmp-utils
      Rocky: *redhat_snmpwalk_package
      Suse:
        - net-snmp
    snmpd_snmpwalk_package: "{{ _snmpd_snmpwalk_package[ansible_os_family] | default(_snmpd_snmpwalk_package['default']) }}"

  tasks:
    - name: install snmpwalk
      ansible.builtin.package:
        name: "{{ snmpd_snmpwalk_package }}"
      notify:
        - remove snmpwalk

    - name: try snmpwalk
      ansible.builtin.command:
        cmd: snmpwalk -v1 -c public localhost

  handlers:

    - name: remove snmpwalk
      ansible.builtin.package:
        name: "{{ snmpd_snmpwalk_package }}"
        state: absent
